name: AI-Powered Security Review

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: AI Security Analysis
    
    permissions:
      contents: read
      security-events: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        npm install -g snyk
        npm install || true
        
    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
    - name: Run Snyk Code Analysis (Enhanced Debug)
      id: snyk-scan
      run: |
        echo "Starting explicit Snyk Code scan..."
        
        # Ensure we're scanning code, not just dependencies
        echo "Running snyk code test with full debugging..."
        snyk code test --json --sarif-file-output=snyk-results.sarif > snyk-results.json 2>&1 || true
        
        echo "=== Raw Snyk Output ==="
        cat snyk-results.json || echo "No JSON output"
        
        echo "=== SARIF Output Check ==="
        ls -la snyk-results.sarif || echo "No SARIF file"
        
        # Try alternative scan methods if first fails
        if [ ! -s snyk-results.json ] || [ "$(cat snyk-results.json)" = "" ]; then
          echo "Primary scan failed, trying alternatives..."
          
          # Method 2: Scan specific files
          snyk code test src/ --json > snyk-results.json 2>&1 || true
          
          # Method 3: Force all project scanning
          snyk code test --all-projects --json > snyk-results.json 2>&1 || true
        fi
        
        echo "=== Final Results Check ==="
        cat snyk-results.json | head -50
        
        # Extract metrics (with better error handling)
        if [ -f snyk-results.json ] && [ -s snyk-results.json ]; then
          # Check if it's valid JSON first
          if jq empty snyk-results.json 2>/dev/null; then
            TOTAL_ISSUES=$(jq '.vulnerabilities | length' snyk-results.json 2>/dev/null || echo "0")
            HIGH_ISSUES=$(jq '.vulnerabilities | map(select(.severity == "high")) | length' snyk-results.json 2>/dev/null || echo "0")
            CRITICAL_ISSUES=$(jq '.vulnerabilities | map(select(.severity == "critical")) | length' snyk-results.json 2>/dev/null || echo "0")
          else
            echo "Invalid JSON output from Snyk"
            TOTAL_ISSUES=0
            HIGH_ISSUES=0
            CRITICAL_ISSUES=0
          fi
        else
          echo "No results file generated"
          TOTAL_ISSUES=0
          HIGH_ISSUES=0
          CRITICAL_ISSUES=0
        fi
        
        echo "Final counts: Total=$TOTAL_ISSUES, High=$HIGH_ISSUES, Critical=$CRITICAL_ISSUES"
        
        echo "high_issues=$HIGH_ISSUES" >> $GITHUB_OUTPUT
        echo "critical_issues=$CRITICAL_ISSUES" >> $GITHUB_OUTPUT
        echo "total_issues=$TOTAL_ISSUES" >> $GITHUB_OUTPUT

        
    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk-results.sarif
        category: snyk-code
        
    - name: Security Gate Check
      if: steps.snyk-scan.outputs.critical_issues > 0 || steps.snyk-scan.outputs.high_issues > 0
      run: |
        echo "❌ Security Gate Failed!"
        echo "Critical Issues: ${{ steps.snyk-scan.outputs.critical_issues }}"
        echo "High Severity Issues: ${{ steps.snyk-scan.outputs.high_issues }}"
        echo "This pull request cannot be merged until security issues are resolved."
        exit 1
        
    - name: Log Security Metrics
      if: always()
      run: |
        python .github/scripts/log-metrics.py \
          --pr-number ${{ github.event.number }} \
          --total-issues ${{ steps.snyk-scan.outputs.total_issues }} \
          --high-issues ${{ steps.snyk-scan.outputs.high_issues }} \
          --critical-issues ${{ steps.snyk-scan.outputs.critical_issues }} \
          --commit-sha ${{ github.sha }}
          
    - name: Upload Security Metrics
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-metrics-${{ github.event.number }}
        path: |
          security-metrics-*.json
          metrics-summary.txt
          snyk-results.json
          snyk-results.sarif

